import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Test() {
  var a1 = 11;
  console.log(a1);
  return (
    <div className="">
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <h1>Test77</h1>
      </div>
    </div>
  )
}
